// data.js
export const foodPlans = [
  {
    energyRange: [1601, 1800],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 8.5 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 8.5 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
];
